### PR TITLE
refactor: allow anyone to add contracts to the registry

### PR DESCRIPTION
**Pull request by chiefbiiko**
# Summary of changes

Removes the root access modifier for adding contracts to the registry. 

## Acceptance Checklist

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue):
    - [x] Have you **written tests **to protect against future occurrences of the bug?
- [ ] New feature (non-breaking change which adds functionality)
    - [ ] Have you **seen it working** in a development environment?
    - [ ] Have you **written tests** for **happy** and **unhappy** paths?
    - [ ] Have you implemented this feature as per the **issue acceptance criteria**?
- [ ] Breaking change (a feature that would cause existing functionality not to work as expected
    - [ ] Is the breaking change **documented**?
    - [ ] Has any previous changes been **deprecated**?
- [ ] CI/CD
    - [ ] If introducing new actions, have you **looked at the action code** for anything spurious?
    - [ ] Have you written **custom scripts** for things that could be actions already on the marketplace?
    - [ ] If introducing new actions, have you **pegged a static version**?
- [ ] Documentation Update
    - [ ] Have you checked other documentation, such as the docs repository?
    - [ ] If updating script documentation, have you **tested it on both environments**?
- [ ] Substrate
    - [ ] RPC methods?
    - [ ] Chainspec, both JSON specs & the module?
    - [ ] Runtime versioning?
    - [ ] Benchmarks?
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by AwesomeIbex — CHANGES_REQUESTED** [review]
Needs the contract registry to be sanitised(ticket in 3vm) since we weren't actually planning on releasing it yet. Why does this need unsudo right now?

**Review by MaciejBaj — CHANGES_REQUESTED** [review]
need to fix the tests

**Comment by ahkohd** [comment]
@chiefbiiko, do you happen to have any update on the PR? It has been a while since it, has received updates.

**Comment by petscheit** [comment]
I dont think this is a good idea, since we don't check if the abi matches the bytecode. Could be used in a bad way I believe

**Comment by AwesomeIbex** [comment]
Lets close this, we have sudo anyway.

Contracts registry needs work.

**Pull request closed without merging**
