### PR TITLE
Migrate Execution-Delivery to Polkadot-v0.9.12 - Closes #180 

### LINKED ISSUE #180: Upgrade Circuit pallets to Substrate v0.9.12
### Description

Upgrade Circuit pallets to substrate v0.9.12

### Acceptance Criteria
Upgrade pallets:
- [x] beefy-merkle-tree
- [x] beefy-mmr-pallet
- [x] contracts-registry
- [ ] execution-delivery
- [x] multi-finality-verifier
- [x] xdns

### PR DESCRIPTION
**Pull request by beqaabu**
Closes #180

### CODE REVIEW

**Review by zannis — COMMENTED** [review]
Kind of impossible to go through the changes so I'm going to 🟢  it as it's not breaking anything and we can look at it in depth on `circuit-parachain`

**Review by zannis — APPROVED** [review]

**Comment by beqaabu** [comment]
@zannis it's still a WIP

**Review by nazar-pc — COMMENTED** [review]
Consider using https://doc.rust-lang.org/cargo/reference/workspaces.html, it will result in a single Cargo.toml for the whole repo and this PR will get quite a bit lighter in terms of lines of code added.

**Comment by MaciejBaj** [comment]
@nazar-pc interesting one, especially for the standalone runtime @zannis . we'll keep the workspaces in mind 👍

**Review by MaciejBaj — APPROVED** [review]

**Pull request merged**
