### PR TITLE
Add token symbol, decimals, and SS58 prefix to XDNS records - Closes #177

### LINKED ISSUE #177: Add TokenSymbol and SS58 prefix to XDNS Records
### Description
Information regarding the TokenSymbol and SS58 prefixes for external gateways is currently missing from the XdnsRecord implementation. We need to add it in order to supply this information to other txns or infrastructure parts like relayers.

TokenSymbol and ss58 prefix should be required in order to instantiate a new record. They can be fetched from the `system_properties` RPC call on any given Substrate-based chain.

### Acceptance Criteria
- [ ] XdnsRecords contain TokenSymbol
- [ ] XdnsRecords contain SS58 prefix
- [ ] Processes that add XdnsRecords to circuit should fetch and add these 2 properties
- [ ] Tests should be updated where necessary, ensuring these properties are properly managed
- [ ] Update @t3rn/types

### PR DESCRIPTION
**Pull request by chiefbiiko**
Introduces a new primitive `GatewaySysProps` and adds it to `XdnsRecord`:

+ also adds `token_decimals` - ok?

+ not using Substrate's JSON-RPC method `system_properties` as it only returns a loosely typed value

	=> hardcoded info from [the ss58 registry](https://wiki.polkadot.network/docs/build-ss58-registry) in a `TryFrom<&ChainId>` impl

Couldn't find `@t3rn/types` :)

Closes #177

### CODE REVIEW

**Review by vedhavyas — APPROVED** [review]
LGTM

**Comment by zannis** [comment]
Great work @chiefbiiko ! You're right about the @t3rn/types, they haven't been merged to the development branch yet, they're on the `kusama-circuit` branch with a pending README and proper CI passing.

Really appreciate your effort and the proactive add of token decimals as well. :) 

If you don't mind, please wait a bit until that one is merged on development so we can tick off that last bullet from the acceptance criteria list before I approve and merge this one. Cheers! 🍻

**Comment by zannis** [comment]
As a followup, latest `development` branch now includes the type definitions, so please add this new struct under `client/types/src/xdns/definitions.ts`.

**Comment by chiefbiiko** [comment]
hey guys, sorry for the delay

so, i finally followed the steps in `client/types/README.md`

now stuck at `execution_delivery.test.ts#registerGateway()` bailing `error TS2554: Expected 9 arguments, but got 10.`

locally, after building, `client/types/dist/augment-api-tx.d.ts` has the updated signature and tests pass

what am i missing?

**Comment by MaciejBaj** [comment]
@chiefbiiko it's on our end, gonna reload the private host that responds of JS-integration tests. 

Many thanks for amazing work! will merge now as all of the other CI steps are passing

**Review by MaciejBaj — APPROVED** [review]

**Pull request merged**
