### PR TITLE
Commit Linting during pipeline execution

### PR DESCRIPTION
**Pull request by phpengine**
## Summary
Feat: Adds linting to commits, grouping them on release, and ensuring commit messages fit the conventional commits standard
Fix: Adds version number to the Pull Request alert GH Workflow step, as specific versioning is required

### CODE REVIEW

**Review by AwesomeIbex — DISMISSED** [review]

**Review by chiefbiiko — CHANGES_REQUESTED** [review]
Would add commit linting as a step under the `lint` job in the `circuit.yml ~ Circuit Build & Test CI` pipeline. Also, please use the latest version of the action.

**Comment by AwesomeIbex** [comment]
> Would add commit linting as a step under the `lint` job in the `circuit.yml ~ Circuit Build & Test CI` pipeline. Also, please use the latest version of the action.

I don't think that's required, it isn't relevant to circuit not the build pipeline. This would still block the pr from merging and we should try to steer away from mono-ci

**Comment by chiefbiiko** [comment]
> > Would add commit linting as a step under the `lint` job in the `circuit.yml ~ Circuit Build & Test CI` pipeline. Also, please use the latest version of the action.
> 
> I don't think that's required, it isn't relevant to circuit nor the build pipeline. This would still block the pr from merging and we should try to steer away from mono-ci
> 
> It would also take longer since this job can be async whilst the others are ongoing.

yea, would increase the std pipeline duration a little bit but would want it to actually fail if commits haven't been massaged..dirty commits shouldn't be merged.

**Comment by phpengine** [comment]
Hi, not sure how this happened...
`[phpengine](https://github.com/phpengine) dismissed [AwesomeIbex](https://github.com/AwesomeIbex)’s [stale review](https://github.com/t3rn/t3rn/pull/393#pullrequestreview-1037019919) via [b203439](https://github.com/t3rn/t3rn/commit/b203439084085a837fc193fb0fb92a5ccc7f2d38) 4 minutes ago`

**Review by AwesomeIbex — APPROVED** [review]

**Review by MaciejBaj — APPROVED** [review]

**Pull request merged**
