### PR TITLE
Adding more info for docker user guide in docs

### PR DESCRIPTION
**Pull request by SPapkovich**
## Summary
[Minor] Updating/adding info for docker part of collator installation guide.

## Checklist
- [ ] insert any notable changes, in order of commit

## Please check that your PR completes the requirements as follows
- [ ] Tests have been added for bug fixes/features
- [ ] Acceptance criteria from the issue has been completed

### CODE REVIEW

**Comment by SPapkovich** [comment]
Also:
- Aura link is broken, need to decide what to do with this line.
- Where "curl" for generating new session key pair should should be executed? If inside the docker container - there is no "curl" installed. Maybe, should be clarified to avoid misunderstandings.

**Comment by MaciejBaj** [comment]
thanks for that @SPapkovich

**Comment by SPapkovich** [comment]
@MaciejBaj You are welcome.
If you will need assistence in writing and verifying docs, docker image composing, CI/CD design - feel free to contact me. Will be glad to help

**Comment by SPapkovich** [comment]
Will remake it with additional items.

**Pull request closed without merging**
