### PR TITLE
fix: successful USDT and TRN XCM transfers using CLI

### PR DESCRIPTION
**Pull request by chexware**
### Summary by CodeRabbit

- New Feature: Added support for limiting the weight of transfer operations and handling different asset types in XCM transfers.
- New Feature: Introduced an extra `SpeedMode::Instant` for faster processing.
- Refactor: Updated signing operations to use pre-hashed message data for improved accuracy and reliability.
- New Feature: Added functionality to add a remote order address with root access in XDNS.
- Chore: Updated runtime version numbers in t0rn-parachain configuration.
- Documentation: Clarified assumptions about indexed fields in the `get_sfx_transfer_asset_abi` function comment.
- Test: Added new test cases for verifying ECDSA signatures and testing the functionality of adding a remote order address.
- Chore: Added `eth2-proof` npm package.

### CODE REVIEW

**Review by 3h4x — APPROVED** [review]
lgtm!

**Review by MaciejBaj — APPROVED** [review]

**Review by 3h4x — CHANGES_REQUESTED** [review]
CHANGELOG.md those changes shouldnt be in the PR

**Comment by chexware** [comment]
> CHANGELOG.md those changes shouldnt be in the PR

Yeah seems like those got intrdouced when merging with development... Will add my changes on a new branch

**Review by 3h4x — APPROVED** [review]

**Comment by 3h4x** [comment]
> > CHANGELOG.md those changes shouldnt be in the PR
> 
> Yeah seems like those got intrdouced when merging with development... Will add my changes on a new branch

you can just use `git checkout origin/development -- README.md` and commit it

**Comment by 3h4x** [comment]
@chexware but also you have on this branch speedmode instant changes which are breaking runtime upgrade.
This is why zombienet test fails.

**Comment by chexware** [comment]
Moved changes to a new branch https://github.com/t3rn/t3rn/pull/1392

**Pull request closed without merging**
